### ISSUE TITLE
GoKart Gen no working

### ISSUE THREAD

**Issue by yelloalejo** [i4M1k0SU/GatherCheat#1]
GoKart Gen no working, just at race field teleport to a kart

**Comment by i4M1k0SU** [comment]
@yelloalejo 

Thank you for reporting the issue.

It is no longer possible to use this feature due to an update on the Gather.town side.

Unfortunately, this feature will be removed.

**Comment by i4M1k0SU** [comment]
Removed the feature and published.

Currently pending review by Google.
